name: Python Project CI/CD

on:
  push:
    paths:
      - 'python-project/**' # sadece python klasöründe değişiklik olursa çalış
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        cd python-project
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd python-project
        pytest # Eğer projede test varsa burası çalışır
